vm_attacker = "attacker"
vm_target = "target"
vm_memory = 1024

Vagrant.configure(2) do |config|
	config.vm.box = "debian/bookworm64"
	config.vm.synced_folder '../', '/home/vagrant/ft_malcolm'
	config.vm.define vm_attacker do |control|
		control.vm.hostname = vm_attacker
		control.vm.network "private_network",
		    ip: "192.168.56.110",
		    virtualbox__intnet: true
		control.vm.provider "virtualbox" do |vb|
			vb.memory = vm_memory
			vb.cpus = 1
			vb.gui = false
			vb.name = vm_attacker
			vb.linked_clone = true
			vb.customize ["modifyvm", :id, "--name", vm_attacker]
		end
    control.vm.provision "shell", inline: <<-EOF
        apt-get update
        apt-get install -y build-essential
        EOF
	end
	config.vm.define vm_target do |control|
		control.vm.hostname = vm_target
		control.vm.network "private_network",
		    ip: "192.168.56.111",
		    virtualbox__intnet: true
		control.vm.provider "virtualbox" do |vb|
			vb.memory = vm_memory
			vb.cpus = 1
			vb.gui = false
			vb.name = vm_target
			vb.linked_clone = true
			vb.customize ["modifyvm", :id, "--name", vm_target]
		end
	end
end